language: generic

sudo: required

services: docker

before_install:
  - docker build -t the2792/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true the2792/react-test-app npm run test -- --coverage

after_success:
  - docker build -t the2792/docker-multi-container-app-frontend ./frontend
  - docker build -t the2792/docker-multi-container-app-backend ./backend
  - docker build -t the2792/docker-multi-container-app-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin # login dockerhub

  - docker push the2792/docker-multi-container-app-frontend
  - docker push the2792/docker-multi-container-app-backend
  - docker push the2792/docker-multi-container-app-nginx