language: generic

sudo: required

services: docker

before_install:
  - docker build -t the2792/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true the2792/react-test-app npm run test -- --coverage

after_success:
  - docker build -t the2792/docker-multi-container-app-frontend ./frontend
  - docker build -t the2792/docker-multi-container-app-backend ./backend
  - docker build -t the2792/docker-multi-container-app-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin # login dockerhub

  - docker push the2792/docker-multi-container-app-frontend
  - docker push the2792/docker-multi-container-app-backend
  - docker push the2792/docker-multi-container-app-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-multi-container-app
  env: Dockermulticontainerapp-env
  bucket_name: elasticbeanstalk-ap-northeast-1-258215388708
  bucket_path: docker-multi-container-app
  on:
    branch: master # 어떤 브랜치에 Push 를 할때 AWS 에 배포를 할 것인지
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY