version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true

  nginx:
    restart: always # no, always, on-failure: 실패할때, unless-stooped: 개발자가 멈추려고할때만
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - mysql

  mysql:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: ./mysql
    restart: "unless-stopped"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}