version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    stdin_open: true

  nginx:
    restart: always # no, always, on-failure: 실패할때, unless-stooped: 개발자가 멈추려고할때만
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend